# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rubygem-foreman_maintain.spec

# add or remove files that should be synced
files_to_sync:
  - rubygem-foreman_maintain.spec
  - foreman_maintain.logrotate

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: foreman_maintain
# downstream (Fedora) RPM package name
downstream_package_name: rubygem-foreman_maintain

upstream_tag_template: v{version}

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/foreman/rubygem-foreman_maintain/rubygem-foreman_maintain.spec -O rubygem-foreman_maintain.spec"
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/foreman/rubygem-foreman_maintain/foreman_maintain.logrotate -O foreman_maintain.logrotate"
  get-current-version:
    - ruby -rrubygems -e 'puts Gem::Specification::load(Dir.glob("*.gemspec").first).version'
  create-archive:
    - gem build foreman_maintain.gemspec
    - bash -c "ls -1t ./foreman_maintain-*.gem | head -n 1"

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      rhel-9:
        additional_repos:
          - https://yum.theforeman.org/releases/nightly/el$releasever/$basearch/
    module_hotfixes: true
  - job: tests
    trigger: pull_request
    targets:
      rhel-9-x86_64:
        distros:
          - centos-stream-9
    tf_extra_params:
      environments:
        - artifacts:
            - type: repository
              id: https://yum.theforeman.org/releases/nightly/el9/x86_64/
              packages:
                - foreman-release

srpm_build_deps:
  - wget
  - rubygems
