Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Features can contain version numbers
Naming/ClassAndModuleCamelCase:
  Exclude:
    - '**/definitions/**/*'
    - 'test/support/additional_definitions/**/*'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/foreman_maintain/system_helpers.rb'

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'lib/foreman_maintain/cli.rb'
    - 'lib/foreman_maintain/cli/**/*'

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Ruby 1.8.7
Style/EachWithObject:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Security/YAMLLoad:
 Enabled: false

# default 10 lines seems to be too constraining, especially when trying to do
# some proper logging
Metrics/MethodLength:
  Max: 15

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  StyleGuide: '#percent-i'
  Enabled: false

Style/InverseMethods:
  Enabled: false

# disabled for reason: It has many false positives including this (bbatsov/rubocop#5223)
Style/FormatStringToken:
  EnforcedStyle: template
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
