# This are the top-level modules to be used in definitions

module Features
end

module Checks
end

module Procedures
end

module Scenarios
end

# do not include this names in autogenerated labels
ForemanMaintain::Concerns::Metadata.top_level_modules = [Features, Checks, Procedures, Scenarios]
